### ISSUE TITLE
Openforcefields versions

### ISSUE THREAD

**Issue by j-wags** [openmm/openmmforcefields#115]
This table will be updated as a part of the openforcefields release process, per https://github.com/openforcefield/openforcefields/wiki/Release-Process

Close this issue once https://github.com/openforcefield/openforcefield/issues/477 is implemented
| Filename | DOI | FF line | Release Date | Change in functional form? |
| -------- | --- | -------- | --- | --- |
| `openff-2.0.0.offxml` |  | Sage | Late 2020 or Early 2021 (Anticipated) | Likely |
| `openff_unconstrained-2.0.0.offxml` |  | Sage | Late 2020 or Early 2021 (Anticipated) | Likely |
| `openff-1.2.0.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3872244.svg)](https://doi.org/10.5281/zenodo.3872244) | Parsley | May 29, 2020 | No |
| `openff_unconstrained-1.2.0.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3872244.svg)](https://doi.org/10.5281/zenodo.3872244) | Parsley | May 29, 2020 | No |
| `openff-1.1.1.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3751818.svg)](https://doi.org/10.5281/zenodo.3751818) | Parsley | Apr 14, 2020 | No |
| `openff_unconstrained-1.1.1.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3751818.svg)](https://doi.org/10.5281/zenodo.3751818) | Parsley | Apr 14, 2020 | No |
| `openff-1.1.0.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3695094.svg)](https://doi.org/10.5281/zenodo.3695094) | Parsley | Mar 3, 2020 | No |
| `openff_unconstrained-1.1.0.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3695094.svg)](https://doi.org/10.5281/zenodo.3695094) | Parsley | Mar 3, 2020 | No |
| `openff-1.0.1.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3751812.svg)](https://doi.org/10.5281/zenodo.3751812) | Parsley | Apr 14, 2020 | No |
| `openff_unconstrained-1.0.1.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3751812.svg)](https://doi.org/10.5281/zenodo.3751812) | Parsley | Apr 14, 2020 | No |
| `openff-1.0.0.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3483227.svg)](https://doi.org/10.5281/zenodo.3483227) | Parsley | Oct 12, 2019 | No |
| `openff_unconstrained-1.0.0.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3483227.svg)](https://doi.org/10.5281/zenodo.3483227) | Parsley | Oct 12, 2019 | No |
| `openff-1.0.0-RC2.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3473554.svg)](https://doi.org/10.5281/zenodo.3473554) | None | Oct 4, 2019 | No |
| `openff_unconstrained-1.0.0-RC2.offxml` | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3473554.svg)](https://doi.org/10.5281/zenodo.3473554) | None | Oct 4, 2019 | No |
| `openff-1.0.0-RC1.offxml` | None | None | Oct 4, 2019 | N/A |
| `openff_unconstrained-1.0.0-RC1.offxml` | None | None | Oct 4, 2019 | N/A |

**Comment by j-wags** [comment]
(to trigger a notification) I've updated the table above to include `openff-1.2.0`. The omnia package will be available shortly.

**Comment by jchodera** [comment]
@j-wags points out that [this code](https://github.com/openforcefield/openforcefields/blob/master/openforcefields/tests/test_openforcefields.py#L19-L26) will automatically discover all installed force fields!
```python
def find_all_offxml_files():
    """Return a list of the offxml files shipped with the package."""
    file_names = []
    for dir_path in get_forcefield_dirs_paths():
        file_pattern = os.path.join(dir_path, '*.offxml')
        file_paths = [file_path for file_path in glob.glob(file_pattern)]
        file_names.extend([os.path.basename(file_path) for file_path in file_paths])
    return file_names

```

**Comment by mattwthompson** [comment]
@jchodera now that 0.7.1 is online, this snippet below is supported out of the box. It's pretty much the same code, but in one place as a public API point


```
In [1]: import openforcefield; print(openforcefield.__version__)
0.7.1

In [2]: from openforcefield.typing.engines.smirnoff.forcefield import get_available_force_fields

In [3]: get_available_force_fields()
Out[3]:
['openff-1.0.1.offxml',
 'openff-1.1.1.offxml',
 'openff-1.0.0-RC1.offxml',
 'openff-1.2.0.offxml',
 'openff_unconstrained-1.0.0-RC2.offxml',
 'openff_unconstrained-1.1.0.offxml',
 'openff_unconstrained-1.0.0.offxml',
 'openff-1.1.0.offxml',
 'openff-1.0.0.offxml',
 'openff-1.0.0-RC2.offxml',
 'openff_unconstrained-1.0.0-RC1.offxml',
 'openff_unconstrained-1.2.0.offxml',
 'openff_unconstrained-1.0.1.offxml',
 'openff_unconstrained-1.1.1.offxml',
 'smirnoff99Frosst-1.0.2.offxml',
 'smirnoff99Frosst-1.0.0.offxml',
 'smirnoff99Frosst-1.1.0.offxml',
 'smirnoff99Frosst-1.0.4.offxml',
 'smirnoff99Frosst-1.0.8.offxml',
 'smirnoff99Frosst-1.0.6.offxml',
 'smirnoff99Frosst-1.0.3.offxml',
 'smirnoff99Frosst-1.0.1.offxml',
 'smirnoff99Frosst-1.0.5.offxml',
 'smirnoff99Frosst-1.0.9.offxml',
 'smirnoff99Frosst-1.0.7.offxml']

In [4]: get_available_force_fields(full_paths=True)
Out[4]:
['/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff-1.0.1.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff-1.1.1.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff-1.0.0-RC1.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff-1.2.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff_unconstrained-1.0.0-RC2.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff_unconstrained-1.1.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff_unconstrained-1.0.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff-1.1.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff-1.0.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff-1.0.0-RC2.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff_unconstrained-1.0.0-RC1.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff_unconstrained-1.2.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff_unconstrained-1.0.1.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/openforcefields-1.2.0-py3.7.egg-tmp/openforcefields/offxml/openff_unconstrained-1.1.1.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.2.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.1.0.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.4.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.8.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.6.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.3.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.1.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.5.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.9.offxml',
 '/Users/mwt/Library/Caches/Python-Eggs/smirnoff99frosst-1.1.0-py3.7.egg-tmp/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.7.offxml']
```
