### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dotsdl** [openmm/openmmforcefields#125]
@jchodera, is a new release imminent? This is now the only blocker for merging [updates for running OpenMM under QCEngine](https://github.com/MolSSI/QCEngine/pull/239). Let me know if there's anything you'd like help with to expedite.

**Comment by jchodera** [comment]
The new release with `openforcefield 0.7.0` support was just cut today:
https://github.com/openmm/openmmforcefields/releases/tag/0.7.4

I've created the new conda package here:
https://travis-ci.org/github/omnia-md/conda-recipes/builds/701717895
I'm just trying to work through some travis issues to get it built and pushed.

As long as you use the newly-released OpenMM 7.4.2, `openmmforcefields` will be able to generate SMIRNOFF parameters.

**Comment by dotsdl** [comment]
Ah cool, thank you @jchodera! I'll stand by and keep an eye out for the conda packages. I'll be able to re-kick CI on that PR to get it passed and merged.

**Comment by jchodera** [comment]
@dotsdl : Any idea what is going on here?
https://travis-ci.org/github/omnia-md/conda-recipes/jobs/701717896#L1225-L1382

**Comment by dotsdl** [comment]
Taking a look now.

**Comment by dotsdl** [comment]
See here: https://github.com/conda/conda-build/issues/3915

May be related to our running an old `conda` in our Docker images; I see version 4.3.34 in `jchodera/omnia-linux-anvil:texlive18-cuda92`, for example.

Are we dependent on a specific version of `conda` and `conda-build` for any particular reason?

**Comment by jchodera** [comment]
Welp, if you're going to tug at that thread, be careful not to unravel the whole sweater. 

Here's the _start_ of our attempt to update to more recent conda-build:
https://github.com/omnia-md/conda-recipes/pull/1010

We had a bit more success in the `conda-recipes-cuda` recently, but haven't ported that over here yet:
https://github.com/omnia-md/conda-recipes-cuda

@jaimergp, @lnaden, and I were hoping we could migrate `openmm` to conda-forge and then deprecate this whole build infrastructure by migrating all packages here to `conda-forge` so we _didn't_ have to rework the entire omnia package build infrastructure, but looks like we may not be able to do that. Unless there's something minor triggering this right now?

**Comment by dotsdl** [comment]
> Welp, if you're going to tug at that thread, be careful not to unravel the whole sweater.

Oh no...yeah, I'll admit this approach is a bit bull-in-a-china-shop. Wasn't fully aware of the depth of the issues at play here. I will consider lighter alternatives.

**Comment by jchodera** [comment]
We've now cut a new release!
https://github.com/openmm/openmmforcefields/releases/tag/0.9.0

**Comment by jaimergp** [comment]
Building package here https://github.com/conda-forge/staged-recipes/pull/13448
