### ISSUE TITLE
implementation / README inconsistency?

### ISSUE THREAD

**Issue by yuanqing-wang** [openmm/openmmforcefields#143]
Hi @jchodera ,

The README of the repo seems to indicate that we can already use `SystemGenerator` with `openforcefield.Topology`,
```
# Create an OpenMM System from an Open Force Field toolkit Topology object
system = system_generator.create_system(openforcefield_topology)
```
whereas it seems that this hasn't been implemented yet. https://github.com/openmm/openmmforcefields/blob/2b568663a897200f1c7c6e5365228eb3450103d7/openmmforcefields/generators/system_generators.py#L293

**Comment by jchodera** [comment]
Fixed in #151
