### ISSUE TITLE
Add phosaa14SB parameters for phosphorylated amino acids

### ISSUE THREAD

**Issue by jchodera** [openmm/openmmforcefields#144]
AmberTools20 adds `phosaa14SB` and `phosaa19SB` parameter sets:
![image](https://user-images.githubusercontent.com/3656088/104208727-ac674f80-53e5-11eb-8725-a4adcf299bc3.png)
We should be able to add `phosaa14SB`, though 19SB is still waiting on CMAP support in parmed (#75)

cc @ppxasjsm

**Comment by ppxasjsm** [comment]
Thanks for raising this!

**Comment by jchodera** [comment]
This was added in #151 and should be in the package we push to conda-forge!
