### ISSUE TITLE
Migrate to GitHub Actions?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmmforcefields#147]
@jaimergp : Would you be able to help migrate this repo to use GitHub actions?

Or is this something I should be able to easily use the cookiecutter to upgrade?

**Comment by jchodera** [comment]
It looks like I can't update the encrypted OpenEye license with `travis encrypt-file`, which seems to be dead.

**Comment by jaimergp** [comment]
Looks like @SimonBoothroyd was faster! :D

**Comment by jchodera** [comment]
Thanks, everybody! Still debugging this.
