### ISSUE TITLE
Add support for GLYCAM06j-1 glycan force fields

### ISSUE THREAD

**Issue by jchodera** [openmm/openmmforcefields#150]
This is currently blocked by https://github.com/ParmEd/ParmEd/issues/1136

**Comment by jchodera** [comment]
This is waiting on https://github.com/ParmEd/ParmEd/issues

**Comment by tristanic** [comment]
The other challenge with this is that GLYCAM is incompatible with OpenMM's topology-matching approach to assigning templates - there are many templates with the same bond topology, just differing in chirality at one or more sites. ISOLDE works around it by assuming the residue name is correct (i.e. PDB standard), then narrows down to the correct template by looking at which oxygens are bonded to neighboring sugars. But you'd probably also want to be able to support people who've already applied GLYCAM names to the residues.

**Comment by jchodera** [comment]
Added in #156!
