### ISSUE TITLE
[SOLVED] Unable to install openmmforcefields on windows 10 ; UnsatisfiableError: The following specifications were found to be incompatible with each other

### ISSUE THREAD

**Issue by jovhuffe** [openmm/openmmforcefields#157]
Hi
I'm unable to install openmmforcefields module on my windows 10 64x desktop PC.
When I tried doing it via anaconda navigator 2020.11, I get this output:

  
    UnsatisfiableError: The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
  

When I tried running it via conda command prompt (as admin), I get the same results:

    (base) C:\Users\jovhuffe>conda activate py38
    
    (py38) C:\Users\jovhuffe>conda install --yes -c conda-forge openmmforcefields
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: -
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed
    
    UnsatisfiableError: The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
    
    
    (py38) C:\Users\jovhuffe>conda search openmmforcefields --channel conda-forge
    Loading channels: done
    # Name                       Version           Build  Channel
    openmmforcefields              0.9.0    pyhd8ed1ab_0  conda-forge
    
    (py38) C:\Users\jovhuffe>conda config --add channels omnia
    
    (py38) C:\Users\jovhuffe>conda search openmmforcefields --channel omnia
    Loading channels: done
    # Name                       Version           Build  Channel
    openmmforcefields              0.7.4          py37_0  omnia
    openmmforcefields              0.7.4            py_0  omnia
    openmmforcefields              0.9.0    pyhd8ed1ab_0  conda-forge
    
    (py38) C:\Users\jovhuffe>conda install --yes -c omnia openmmforcefields
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: -
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.\
    failed
    
    UnsatisfiableError: The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
    
    
    (py38) C:\Users\jovhuffe>conda install --yes -c omnia openmmforcefields=0.7.4
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: -
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed
    
    UnsatisfiableError: The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
    
    
    (py38) C:\Users\jovhuffe>conda install --yes -c omnia openmmforcefields==0.7.4
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: |
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort./
    failed
    
    UnsatisfiableError: The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
    
    
    (py38) C:\Users\jovhuffe>conda install -c omnia/label/dev openmmforcefields
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: \
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.|
    Examining @/win-64::__win==0=0:  75%|███████████████████████████████████████             | 3/4 [00:01<00:00,  2.74it/s]-                                                                                                                       \failed
    
    UnsatisfiableError: The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
    
    
    (py38) C:\Users\jovhuffe>

This also shows that conda is clearly able to find the openmmforcefields package but wont install it for some reason.

Prior to attempting this, I had uninstalled the anaconda 2019.03 in favour of the newest 2020.11.
But this doesn't seem to be the problem as I have tried reverting back to it and even tried other different python versions (3.6-3.7-3.9) and compatibilities. None of it seem to work.

I've also tried many different solutions (a.o.) from
https://anaconda.org/search?q=openmmforcefields and https://github.com/openmm/openmmforcefields/tree/0.7.0

I would greatly appreciate some clarification as to what is going on.

Regards

**Comment by jchodera** [comment]
@jaimergp : Any idea what might be going wrong here?

**Comment by jaimergp** [comment]
If we can the error that `mamba` gives, that'd be more descriptive. I guess that some (2nd order?) dependency is not available on Windows.

Install `mamba` with `conda install -n base -c conda-forge mamba` and then use `mamba create -n openmmforcefields -c conda-forge openmmforcefields`.

**Comment by jaimergp** [comment]
I did it in my Windows install:

```
(base) PS C:\Users\Jaime> mamba create -n openmmforcefields -c conda-forge openmmforcefields
pkgs/r/win-64            [====================] (00m:00s) No change
pkgs/msys2/win-64        [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/msys2/noarch        [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/main/win-64         [====================] (00m:02s) Done
conda-forge/noarch       [====================] (00m:03s) Done
conda-forge/win-64       [====================] (00m:06s) Done

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.5) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['openmmforcefields']

Encountered problems while solving.
Problem: nothing provides ambertools >=20.0 needed by openmmforcefields-0.9.0-pyhd8ed1ab_0
```

So `ambertools` is a dependency but it's not available on Windows.

**Comment by jovhuffe** [comment]
> So `ambertools` is a dependency but it's not available on Windows.

So windows users are unable to use openmmforcefields?

That's unfortunate and rather odd, as it would mean that, either all Windows users have this same issue and any version of 'openmmforcefields' does not work for windows, or I would need to revert to a previous openmmforcefield version that does not have this dependency for which I'd love some tips on which one is recommended.

(except cloning the repository and running it from a local folder)

regards

**Comment by jovhuffe** [comment]
For the sake of completeness:

I'm now using linux (ubuntu) and have **not** encountered the same issue.

_To the developers:_ it might be helpfull For any prospective OpenMM users to **mention, in the docs, the fact that openmmforcefields will not be able to install on a native Windows machines.**

The amount of people encountering this issue is surprisingly low to non-existent, and I spent/lost quite a significant amount of time coming to this conclusion.

Thank you for the quick help though :)
