### ISSUE TITLE
Loading charmm35_nowaters.xml uses >12GB of memory and takes >10 min to run

### ISSUE THREAD

**Issue by apayne97** [openmm/openmmforcefields#164]
Since it (apparently?) consumes all memory on my laptop and takes so long to run, I assume something is going wrong, because I haven't seen any problems with any other of the xml files?

Am I missing something?

This is the command I'm using:

`forcefield = app.ForceField('charmm/charmm36_nowaters.xml')`

**Comment by apayne97** [comment]
worked immediately using a jupyter notebook on the cluster so maybe a Mac OS / PyCharm thing is responsible?

**Comment by jchodera** [comment]
@apayne97 : Make sure you have a recent version of OpenMM installed. I seem to recall that there were some performance improvements made at some point.

**Comment by apayne97** [comment]
So I finally just updated openmm using the basic conda forge install to 7.5 on the cluster (previously had been using 7.4.2 on the cluster and 7.5 on my local machine) and saw this runtime / memory issue again. So in this case updating to the newer version created the problem. no error messages or anything, it just never stops consuming more memory and never finishes loading, up to 32Gb of memory on the cluster.

**Comment by peastman** [comment]
It looks like something has gone wrong in the code to identify which patches to allow for which residues.  https://github.com/openmm/openmmforcefields/blob/master/charmm/ffxml/charmm36_nowaters.xml includes over 100 `<AllowPatch>` tags for each standard residue.  Compare to https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/charmm36.xml which only has eight for most of them.

**Comment by apayne97** [comment]
should I open a new issue for this?

**Comment by jchodera** [comment]
@apayne97 : Can you open an issue in https://github.com/openmm/openmmforcefields?

The actual issue may be due to changes in ParmEd, but we can track the issue there.
