### ISSUE TITLE
gaff2 xml is not right

### ISSUE THREAD

**Issue by boyuezhong** [openmm/openmmforcefields#165]
gaff2 xml

Atom type="c" sigma="0.3315212309943831" epsilon="0.4133792"/ 

gaff2 dat
c           1.8606  0.0988

 r=sigma *((2)^(1/6))=0.3315212309943831*((2)^(1/6))=0.37
It is wrong!!!

**Comment by jchodera** [comment]
@boyuezhong : Apologies for only noticing this now!

Note that the [OpenMM ffxml format](http://docs.openmm.org/latest/userguide/application.html#writing-the-xml-file) uses the [OpenMM MD unit system](http://docs.openmm.org/latest/userguide/library.html#units), which is kJ/mol, nanometers, radians, picoseconds, etc. By contrast, parameters in the Amber format use a different unit system (kcal/mol, Anstroms, both radians and degrees, etc.) 

This is why we provide the [`simtk.unit`](http://docs.openmm.org/latest/api-python/app.html#units) package to help interconvert between unit-bearing quantities, and encourage use of unit-bearing quantities whenever possible. The Open Force Field Initiative has also [standardized on including units everywhere](https://open-forcefield-toolkit.readthedocs.io/en/0.9.2/smirnoff.html) in the force field specification to guard against misunderstandings of this nature.

In this particular case, the Amber parameter is rmin = 1.8606*angstroms, which must be converted to sigma via
```
sigma = 2*rmin/2^(1/6) = 2*1.8606*angstroms/2^(1/6) = 0.3315*nanometers
```
