### ISSUE TITLE
Cutting 0.10.0 release to support OpenMM 7.6

### ISSUE THREAD

**Issue by jchodera** [openmm/openmmforcefields#178]
@peastman : Now that we've updated the import paths and incorporated GLYCAM-06j support, is there anything else critical from the OpenMM issue tracker to fix before we release 0.10.0 with `openmm >=7.6` as a requirement, @peastman?

**Comment by peastman** [comment]
Not that I know of (although I wouldn't necessarily know).

**Comment by mikemhenry** [comment]
Closed with https://github.com/conda-forge/openmmforcefields-feedstock/pull/3
