### ISSUE TITLE
implicit solvent with small molecules?

### ISSUE THREAD

**Issue by tanmoy7989** [openmm/openmmforcefields#188]
Hi,

If I include an off-the-shelf implicit solvent model in a protein-ligand binding simulation, would the effects of the implicit solvent model extend to the ligand as well? Eg.  in this example:

`sysgen = SystemGenerator(forecefields=["amber14/protein.ff14SB.xml", "implicit/gbn2.xml"], 
                                              small_molecule_forcefield="gaff-2.11",
                                              forcefield_kwargs={"constraints": HBonds, "hydrogenMass": 4 * unit.amu, },
                                              cache="ligand_db.json") 
`

would the effect of `implicit/gbn2.xml` be applied on top of the `gaff-2.11` parameters to the ligand as well, or would these only be limited to the protein? If not, what might be a good way to do this? 

I can always use explicit solvent of course, but I'm working on a high throughput pipeline without the need for accurate thermodynamics from the MD simulation, so I can make do with implicit solvent.

**Comment by peastman** [comment]
Implicit solvent is applied to the whole system, including the ligand.  The GB models aren't specific to any one type of molecule.  The only features of each atom it cares about are the element and the charge (which it gets from the force field).

**Comment by tanmoy7989** [comment]
@peastman, that sounds great. Thank you so much! Not closing the issue just yet, in case I face issues with this implicit solvent.
