### ISSUE TITLE
Noisy debug prints at INFO logging level

### ISSUE THREAD

**Issue by IAlibay** [openmm/openmmforcefields#200]
We're getting a very noisy outputs at INFO logging levels when using openmmtools.

From what we've seen it's down to what is being fixed in https://github.com/openmm/openmmforcefields/pull/198 and this being set at the warning level instead of debug: https://github.com/openmm/openmmforcefields/blame/ccd6b9daa56743d2c93484bca105d0ed66d13d23/openmmforcefields/generators/template_generators.py#L1072

<s>I'll</s> #199 is open to address the second issue, it would be much appreciated if we could limit the noise from this (the other info logging is really useful and we would prefer not turn off logging output completely).

**Comment by mikemhenry** [comment]
Resolved with #198 and #201
