### ISSUE TITLE
No module named Openforcefield

### ISSUE THREAD

**Issue by manos996** [openmm/openmmforcefields#205]
Hello, i am having some issues with my attempt of adding topology to a small organic molecule for an openmm simulation. There is no template for the ligand, so i try to use residue template generators for small molecules from the [openmmforcefields](http://github.com/openmm/openmmforcefields) conda package. 
I install this via conda with:
$ conda install -c conda-forge openmmforcefields
The installation is successful and then i am getting that error message

**from openforcefield.topology import *
ModuleNotFoundError: No module named 'openforcefield'**

I also attach a screenshot of my .py file.
![Screenshot from 2022-05-26 01-41-59](https://user-images.githubusercontent.com/106256967/170381455-75ecc223-c99c-4d39-8fad-7102449e8b7c.png)

**Comment by peastman** [comment]
You're mixing up  "openmmforcefields" with "openforcefield".  They're different packages!  See https://github.com/openforcefield/openff-toolkit for instructions on installing and using the latter.  The correct import is `from openff.toolkit.topology import *`.

**Comment by manos996** [comment]
@peastman i tried that .py file as i attach, but it didn't work either
![Screenshot from 2022-06-05 22-29-56](https://user-images.githubusercontent.com/106256967/172067377-850c4807-0cd6-413d-8d0f-feb43ef979ce.png)
.
