### ISSUE TITLE
Atom typing always uses GAFF even when GAFF2 specified

### ISSUE THREAD

**Issue by rosemary-cresset** [openmm/openmmforcefields#210]
When parameterising with GAFF2, openmmforcefields uses the following antechamber command: 

`antechamber -i in.mdl -fi mdl -o out.mol2 -fo mol2 -s 0 -at 2 -dr no`

However, the options available to the 'at' flag are gaff, gaff2, amber, bcc, and sybyl. With the current argument of '2', antechamber is defaulting to using GAFF atom types. 

Sometimes this makes no difference as the correct GAFF2 parameters are used by parmchk2, but GAFF2 contains some atom types that GAFF does not, so sometimes it does matter. For example, two of the nitrogens in the attached molecule ([A_MOL_1_0.sdf.txt](https://github.com/openmm/openmmforcefields/files/9082915/A_MOL_1_0.sdf.txt)) are given atom type n by GAFF, but are given atom type ns by GAFF2.

**Comment by jchodera** [comment]
Thanks for catching this! We should be able to get this fixed ASAP.

**Comment by rosemary-cresset** [comment]
Fantastic - thanks very much for the quick fix!
