### ISSUE TITLE
No module named 'openff.units'

### ISSUE THREAD

**Issue by pablo-arantes** [openmm/openmmforcefields#256]
Hi Opemm team,

Thank you for your work. I've been using the OpenMM Force Fields for more than one year, and it was working fine. Today I was trying to run, and I had the following issue:

     93 for deg in range(-180, (180+int(degrees_steps)), int(degrees_steps)):
     94   pdbfile = PDBFile(os.path.join(workDir, "mol_files/" + str(deg) + "_min.pdb"))
     95   system = forcefield.createSystem(pdbfile.topology, nonbondedCutoff=1*nanometer, constraints=HBonds)
     96 
     97   for i, f in enumerate(system.getForces()):
     [/usr/local/lib/python3.8/site-packages/openmmforcefields/generators/template_generators.py](https://localhost:8080/#) in _molecule_has_user_charges(self, molecule)
    220         """
    221         import numpy as np
    222         from openff.units.openmm import ensure_quantity
    223 
    224         if molecule.partial_charges is None:
    ModuleNotFoundError: No module named 'openff.units'

Can you please help me in this error?

Thank you.

Best,

Pablo

**Comment by mattwthompson** [comment]
Try installing `openff-units`, i.e. `mamba install openff-units -c conda-forge`

https://anaconda.org/conda-forge/openff-units/files

**Comment by pablo-arantes** [comment]
Hi @mattwthompson,

Thank you for your inputs, however I've tested in a fresh environment and I had the same issue.

**Comment by mattwthompson** [comment]
How did you create the environment? Please help me reproduce the issue so I can help

**Comment by pablo-arantes** [comment]
Sure, follow the environment: https://colab.research.google.com/drive/1-QAsxMq92szG4-bB1L7QTBtFrMy5OyUp?usp=sharing

**Comment by mattwthompson** [comment]
That notebook produces an environment that looks fine to me:

![image](https://user-images.githubusercontent.com/7935382/207407557-1f9cad57-2957-4519-9a39-08f84f9ef53f.png)

It's pretty slow to recreate, though, and there are several other issues that are likely to cause trouble:

* RDKit is available on conda, and brought in by default by `openff-toolkit`. There's no need to manually install it
* Specifying `openmm=7.6` constrains OpenMM to that version, which may or may not be what you intend. It's brought in by default by `openmmforcefields` _and_ `openff-toolkit`, installing it manually is not necessary
* `conda`/Miniconda are slow, recommend `mamba`/Mambaforge for significantly faster environment solutions
* Mucking around with `sys.path` is dangerous and extremely likely to break installation tooling. For out-of-the-box `conda` on Google Colab, recommend https://github.com/conda-incubator/condacolab. A notebook with the two below cells installs the versions I expect and does so in about 2 minutes:


```
!pip install -q condacolab
import condacolab
condacolab.install()
```

```
!mamba install openmmforcefields -c conda-forge -y

**Comment by pablo-arantes** [comment]
Hi, 

Thank you so much for your inputs. Now it's working fine and with mamba is a faster environment. 

Best,

Pablo
