### ISSUE TITLE
Check if partial charges are preserved when using `from-molecule` charge method in `EspalomaTemplateGenerator`

### ISSUE THREAD

**Issue by ijpulidos** [openmm/openmmforcefields#282]
Good catch! We need to make sure if this is the case because we want users to be able to use charges from other methods/models combined with espaloma. I'll raise an issue about this so we can keep track of this.

_Originally posted by @ijpulidos in https://github.com/openmm/openmmforcefields/pull/271#discussion_r1231611892_

**Comment by ijpulidos** [comment]
One workaround is to make sure we store/save the charges before we apply the espaloma parameters, and then we change them to the original ones after we apply the espaloma parameters. This should be done in the `EspalomaTemplateGenerator`

**Comment by jchodera** [comment]
@ijpulidos : Can you clarify the behavior you want here?

The behavior that is _supposed_ to happen is [described here](https://github.com/openmm/openmmforcefields#partial-charges-for-small-molecules):
> If the provided molecule(s) contain nonzero (user-specified) partial charges, they will be used.

The rest of the documentation in this paragraph is out of date:
> If they do not contain partial charges, the openff-toolkit charging method [Molecule.compute_partial_charges_am1bcc](https://open-forcefield-toolkit.readthedocs.io/en/latest/api/generated/openff.toolkit.topology.Molecule.html#openff.toolkit.topology.Molecule.compute_partial_charges_am1bcc) is used to assign partial charges. The [canonical AM1-BCC charging method](https://docs.eyesopen.com/toolkits/cookbook/python/modeling/am1-bcc.html) is used to assign ELF10 charges if the OpenEye Toolkit is available. If not, [Antechamber](http://ambermd.org/antechamber/) from the [AmberTools](http://ambermd.org/AmberTools.php) distribution (which uses the sqm semiempirical quantum chemical package) is used to assign AM1-BCC charges (antechamber -c bcc).

We should change this to say that the forcefield-specified charge model (graph charges for espaloma, toolkit AM1-BCC specified by the force field for OpenFF) is used if the `Molecule` has zero charges.
