### ISSUE TITLE
Pin to ambertools <= 22 until we can sort out changes to GAFF2 behavior

### ISSUE THREAD

**Issue by jchodera** [openmm/openmmforcefields#286]
cc : #281

**Comment by ijpulidos** [comment]
We need to pin both the package in conda-forge and the test environment dependencies in this repo. Just putting it here as a reminder.

**Comment by mattwthompson** [comment]
The feedstock is already pinned, though it might be wise to also update repodata https://github.com/conda-forge/openmmforcefields-feedstock/pull/11

**Comment by mikemhenry** [comment]
Yes, pinned it back in June (forgot I did that) 
I just did a quick test and `micromamba create -n testfoofoo openmmforcefields` and it pulled in openmmforcefields `0.11.2` and ambertools `22.5` so it looks like the correct stuff is getting pulled in and a repodata patch isn't needed (I know we can still do one, but it is a bit tricky so I don't think it is worth the engineering effort, but I could be convinced).
