### ISSUE TITLE
SystemGenerator support for custom force fields (e.g. from openff-bespokefit)

### ISSUE THREAD

**Issue by arjun-nufc** [openmm/openmmforcefields#299]
I used openff-bespokefit to get custom force field parameters for ligands to do RBFE with Perses.  However when i supply the file for the custom .offxml file to Perses as the small molecule force field, i get the Value Error from line 208 of system_generators.py (release 0.11.2) and associated error message: "No registered small molecule template generators could load force field" .  Does the SystemGenerator class support custom force fields, and if so, how does one do that ?  if not are there plans to do so ?  Thanks

**Comment by mattwthompson** [comment]
`SMIRNOFFTemplateGenerator` has a `forcefield` argument that should be able to parse something from disk. I don't know if Perses is wired up to pass this through from that interface to this one - @ijpulidos?

**Comment by arjun-nufc** [comment]
ah ok thanks Matt.  so this functionality is provided by SMIRNOFFTemplateGenerator and was not intended to be provided by SystemGenerator.  yeah i think Perses specifically calls SystemGenerator.  I can post the issue there then.  Thank you

**Comment by ijpulidos** [comment]
Perses should be able to parse a SMIRNOFF custom FF file if it's in the root directory where you launch perses. Can you share the whole traceback of the error you are getting?

**Comment by ijpulidos** [comment]
Oh I just saw your last message. Yeah, feel free to post the issue there if you think it's specific to perses.

**Comment by arjun-nufc** [comment]
Thanks both, i'll close this and open an issue on the Perses page.
