### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by ZhouChenghui** [openmm/openmmforcefields#301]
Hello admin, I have issue installing openmmforcefields from conda as described on a linux machine. It always has the issues of  unable to solve the environment.  So I've even tried to install this alone after creating the environment with python 3.5, 3.7 and 3.8, however the problem persists. Is there some kind of system requirements that I'm missing here? Thank you!

**Comment by mattwthompson** [comment]
Hey @ZhouChenghui could you share the commands you've used and also the output?

Also, in terms of Python versions, this and related tools implicitly or explicitly follows [NEP 29], so Python 3.9-3.11 are good starting points. 3.7-3.8 might work, whereas 3.5 is now several years out of date.

**Comment by ZhouChenghui** [comment]
Hello, thank you for the info. I was finally able to install with 3.11, but not 3.9. I used the exact command that's on the readme of the github repo, there's not really output other than "solving environment dependencies" and it just keeps on going forever without ever solving it.

**Comment by peastman** [comment]
Try using mamba instead of conda.  It's much faster, and it gives much better error messages.  The README should probably recommend it as well.

**Comment by mattwthompson** [comment]
@ZhouChenghui have you been able to install this package now? OpenFF has written a[ few tips](https://docs.openforcefield.org/en/latest/install.html#installing-mamba-in-an-existing-conda-installation) on usage here that might be useful, including setting up MambaForge from the ground up - I'd also recommend creating a new environment for each new project.

**Comment by ZhouChenghui** [comment]
Hello, I was eventually able to install openforcefields with the higher versions of python. Thank you!
