### ISSUE TITLE
Saving trajectory without wrapping

### ISSUE THREAD

**Issue by CheggQuery** [openmm/openmmforcefields#304]
I am running a Brownian dynamics simulation (_openmm.BrownianIntegrator(300 kelvin, 91/ps, 2 fs)_) for a protein in the presence of ions. I want to calculate the dynamic properties like the translational diffusion coefficient.  For calculating the dynamic properties we need unwrapped trajectories. Therefore, I used dcdreporters as _simulation.reporters.append(app.DCDReporter('traj.dcd',2 fs,enforcePeriodicBox=False))_.

However, after running 2 microseconds, there is only 45 angstrom translation in the center of mass of the protein. Is it enough to write only **enforcePeriodicBox=False** in the dcdreporter to turn off pbc wrapping?

**Comment by mattwthompson** [comment]
I see you've opened the [same issue](https://github.com/openmm/openmm/issues/4254) in OpenMM's issue tracker - that's where this should go, so I'm closing this duplicate.
