### ISSUE TITLE
Fix broken badges

### ISSUE THREAD

**Issue by jchodera** [openmm/openmmforcefields#308]
We should fix the README.md CI and conda-forge badges:
![image](https://github.com/openmm/openmmforcefields/assets/3656088/e6842893-d349-4aa2-a121-3699d75c491e)

@mikemhenry : Are you able to help with this?

**Comment by jchodera** [comment]
We might also want to change the title to be "AMBER, CHARMM, and Espaloma force fields for OpenMM".

**Comment by jchodera** [comment]
Whoops---the examples in the README.md also need to be updated from `espaloma-0.2.2` to `espaloma-0.3.2`:
https://github.com/openmm/openmmforcefields#examples-using-espalomatemplategenerator-to-generate-small-molecule-parameters-with-espaloma

**Comment by jchodera** [comment]
Some of these issues were fixed by @mattwthompson in https://github.com/openmm/openmmforcefields/pull/305!

**Comment by mikemhenry** [comment]
I will fix this badge and do a pass on a few others that looked like they were pointing to old things.

**Comment by mikemhenry** [comment]
Fixed with #309
