### ISSUE TITLE
Exception: Multiple non-identical matching templates found for residue 2 (SER): SER, DSER.

### ISSUE THREAD

**Issue by hungd238** [openmm/openmmforcefields#326]
How do I fix this error while using the PDB file and (forcefield = ForceField("charmm/charmm36_nowaters.xml", "charmm/waters_ions_default.xml") to run the simulations?

raise Exception('Multiple non-identical matching templates found for residue %d (%s): %s.' % (res.index+1, res.name, ', '.join(match[0].name for match in allMatches)))
Exception: Multiple non-identical matching templates found for residue 2 (SER): SER, DSER.

**Comment by peastman** [comment]
You can use the `residueTemplates` argument to `createSystem()`.  The [the API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem) for details.

**Comment by hungd238** [comment]
Thank you very much for your prompt, Dr. Eastman. I actually have my codes as following:
`forcefield = ForceField("charmm/charmm36_nowaters.xml", "charmm/waters_ions_default.xml")

modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
'''
Membrane Embedding and/or System Solvation
'''
modeller.addSolvent(forcefield, model="tip3p", ....)
`
The error already took place at the `modeller.addHydrogens(forcefield)` or `modeller.addSolvent(forcefield, model="tip3p", ....)` lines. 
`    raise Exception('Multiple non-identical matching templates found for residue %d (%s): %s.' % (res.index+1, res.name, ', '.join(match[0].name for match in allMatches)))
Exception: Multiple non-identical matching templates found for residue 2 (SER): SER, DSER.`
I checked the documentation and there seemed to be no way to specify residueTemplates with Modeller. Can you please give me some suggestions? Thank you very much!

**Comment by peastman** [comment]
I would use the built in implementation of CHARMM36 rather than the one from this repository.

```python
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')
```

It doesn't include D-amino acids.

**Comment by hungd238** [comment]
Thank you very much again for your prompt response, Dr. Eastman. Since I have the POPC lipid in my simulation system, if I use **forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')**, then I run into another problem.

This is the atom order of one POPC lipid molecule from the CHARMM36 force field:
**ATOM   5273  N   POPC  320      65.021  63.386  85.827  0.00  0.00            
ATOM   5274  C12 POPC  320      66.148  63.759  86.787  0.00  0.00            
ATOM   5275 H12A POPC  320      66.971  62.940  86.840  0.00  0.00            
ATOM   5276 H12B POPC  320      66.613  64.668  86.522  0.00  0.00            
ATOM   5277  C13 POPC  320      65.597  63.151  84.429  0.00  0.00            
ATOM   5278 H13A POPC  320      64.948  62.589  83.837  0.00  0.00            
ATOM   5279 H13B POPC  320      65.750  64.052  83.834  0.00  0.00            
ATOM   5280 H13C POPC  320      66.493  62.675  84.383  0.00  0.00            
ATOM   5281  C14 POPC  320      64.422  62.156  86.266  0.00  0.00            
ATOM   5282 H14A POPC  320      63.252  62.193  86.107  0.00  0.00            
ATOM   5283 H14B POPC  320      64.747  61.274  85.725  0.00  0.00            
ATOM   5284 H14C POPC  320      64.702  61.861  87.244  0.00  0.00            
ATOM   5285  C15 POPC  320      63.998  64.488  85.639  0.00  0.00            
ATOM   5286 H15A POPC  320      63.273  64.282  84.937  0.00  0.00            
ATOM   5287 H15B POPC  320      63.453  64.686  86.507  0.00  0.00            
ATOM   5288 H15C POPC  320      64.420  65.348  85.278  0.00  0.00            
ATOM   5289  C11 POPC  320      65.702  64.164  88.221  0.00  0.00            
ATOM   5290 H11A POPC  320      66.618  64.141  88.914  0.00  0.00            
ATOM   5291 H11B POPC  320      65.100  63.357  88.751  0.00  0.00            
ATOM   5292  P   POPC  320      65.758  66.801  87.917  0.00  0.00            
ATOM   5293  O13 POPC  320      67.089  66.534  87.391  0.00  0.00            
ATOM   5294  O14 POPC  320      65.632  67.724  89.110  0.00  0.00            
ATOM   5295  O12 POPC  320      65.037  65.438  88.257  0.00  0.00            
ATOM   5296  O11 POPC  320      64.837  67.503  86.839  0.00  0.00            
ATOM   5297  C1  POPC  320      63.513  67.913  87.292  0.00  0.00            
ATOM   5298  HA  POPC  320      62.787  66.977  87.222  0.00  0.00            
ATOM   5299  HB  POPC  320      63.303  68.148  88.333  0.00  0.00            
ATOM   5300  C2  POPC  320      62.921  69.031  86.362  0.00  0.00            
ATOM   5301  HS  POPC  320      61.838  69.231  86.718  0.00  0.00            
ATOM   5302  O21 POPC  320      62.942  68.503  85.018  0.00  0.00            
ATOM   5303  C21 POPC  320      61.969  67.731  84.730  0.00  0.00            
ATOM   5304  O22 POPC  320      60.970  67.500  85.388  0.00  0.00            
ATOM   5305  C22 POPC  320      62.128  67.001  83.372  0.00  0.00            
ATOM   5306  H2R POPC  320      63.136  66.825  83.233  0.00  0.00            
ATOM   5307  H2S POPC  320      61.914  67.786  82.572  0.00  0.00            
ATOM   5308  C3  POPC  320      63.667  70.356  86.458  0.00  0.00            
ATOM   5309  HX  POPC  320      64.773  70.281  86.126  0.00  0.00            
ATOM   5310  HY  POPC  320      63.686  70.592  87.550  0.00  0.00            
ATOM   5311  O31 POPC  320      62.988  71.449  85.837  0.00  0.00            
ATOM   5312  C31 POPC  320      63.393  72.030  84.653  0.00  0.00            
ATOM   5313  O32 POPC  320      63.080  73.180  84.350  0.00  0.00            
ATOM   5314  C32 POPC  320      64.244  71.122  83.736  0.00  0.00            
ATOM   5315  H2X POPC  320      63.774  70.089  83.748  0.00  0.00            
ATOM   5316  H2Y POPC  320      65.327  71.253  84.126  0.00  0.00            
ATOM   5317  C23 POPC  320      61.191  65.794  83.081  0.00  0.00            
ATOM   5318  H3R POPC  320      60.920  65.283  84.066  0.00  0.00            
ATOM   5319  H3S POPC  320      60.218  66.301  82.794  0.00  0.00            
ATOM   5320  C24 POPC  320      61.640  64.734  82.120  0.00  0.00            
ATOM   5321  H4R POPC  320      62.673  64.417  82.422  0.00  0.00            
ATOM   5322  H4S POPC  320      61.020  63.797  82.204  0.00  0.00            
ATOM   5323  C25 POPC  320      61.578  65.115  80.599  0.00  0.00            
ATOM   5324  H5R POPC  320      62.144  64.503  79.894  0.00  0.00            
ATOM   5325  H5S POPC  320      62.038  66.163  80.570  0.00  0.00            
ATOM   5326  C26 POPC  320      60.054  64.855  80.141  0.00  0.00            
ATOM   5327  H6R POPC  320      59.854  63.771  80.240  0.00  0.00            
ATOM   5328  H6S POPC  320      59.393  65.312  80.807  0.00  0.00            
ATOM   5329  C27 POPC  320      59.967  65.165  78.616  0.00  0.00            
ATOM   5330  H7R POPC  320      59.011  64.872  78.299  0.00  0.00            
ATOM   5331  H7S POPC  320      60.704  64.521  78.051  0.00  0.00            
ATOM   5332  C28 POPC  320      60.098  66.664  78.276  0.00  0.00            
ATOM   5333  H8R POPC  320      60.204  66.781  77.164  0.00  0.00            
ATOM   5334  H8S POPC  320      61.125  66.954  78.702  0.00  0.00            
ATOM   5335  C29 POPC  320      59.009  67.559  78.790  0.00  0.00            
ATOM   5336  H91 POPC  320      57.995  67.216  78.423  0.00  0.00            
ATOM   5337 C210 POPC  320      59.155  68.703  79.497  0.00  0.00            
ATOM   5338 H101 POPC  320      58.210  69.211  79.774  0.00  0.00            
ATOM   5339 C211 POPC  320      60.336  69.386  80.082  0.00  0.00            
ATOM   5340 H11R POPC  320      60.964  68.475  80.397  0.00  0.00            
ATOM   5341 H11S POPC  320      60.164  69.852  80.996  0.00  0.00            
ATOM   5342 C212 POPC  320      61.084  70.452  79.267  0.00  0.00            
ATOM   5343 H12R POPC  320      60.386  71.195  78.836  0.00  0.00            
ATOM   5344 H12S POPC  320      61.813  70.934  79.957  0.00  0.00            
ATOM   5345 C213 POPC  320      62.044  69.782  78.203  0.00  0.00            
ATOM   5346 H13R POPC  320      61.423  69.208  77.479  0.00  0.00            
ATOM   5347 H13S POPC  320      62.592  69.005  78.803  0.00  0.00            
ATOM   5348 C214 POPC  320      63.059  70.852  77.686  0.00  0.00            
ATOM   5349 H14R POPC  320      62.386  71.526  77.093  0.00  0.00            
ATOM   5350 H14S POPC  320      63.481  71.464  78.464  0.00  0.00            
ATOM   5351 C215 POPC  320      64.027  70.215  76.749  0.00  0.00            
ATOM   5352 H15R POPC  320      64.337  69.230  77.133  0.00  0.00            
ATOM   5353 H15S POPC  320      63.500  70.055  75.800  0.00  0.00            
ATOM   5354 C216 POPC  320      65.300  71.065  76.497  0.00  0.00            
ATOM   5355 H16R POPC  320      64.996  72.130  76.221  0.00  0.00            
ATOM   5356 H16S POPC  320      65.907  70.640  75.637  0.00  0.00            
ATOM   5357 C217 POPC  320      66.179  71.239  77.724  0.00  0.00            
ATOM   5358 H17R POPC  320      66.220  70.305  78.375  0.00  0.00            
ATOM   5359 H17S POPC  320      65.759  72.058  78.382  0.00  0.00            
ATOM   5360 C218 POPC  320      67.540  71.589  77.202  0.00  0.00            
ATOM   5361 H18R POPC  320      67.558  72.561  76.701  0.00  0.00            
ATOM   5362 H18S POPC  320      68.269  71.632  77.978  0.00  0.00            
ATOM   5363 H18T POPC  320      68.003  70.836  76.562  0.00  0.00            
ATOM   5364  C33 POPC  320      64.514  71.642  82.289  0.00  0.00            
ATOM   5365  H3X POPC  320      64.843  72.654  82.341  0.00  0.00            
ATOM   5366  H3Y POPC  320      63.564  71.757  81.685  0.00  0.00            
ATOM   5367  C34 POPC  320      65.610  70.850  81.575  0.00  0.00            
ATOM   5368  H4X POPC  320      66.495  70.828  82.281  0.00  0.00            
ATOM   5369  H4Y POPC  320      65.986  71.434  80.604  0.00  0.00            
ATOM   5370  C35 POPC  320      65.364  69.404  81.248  0.00  0.00            
ATOM   5371  H5X POPC  320      64.525  69.350  80.482  0.00  0.00            
ATOM   5372  H5Y POPC  320      65.060  68.889  82.220  0.00  0.00            
ATOM   5373  C36 POPC  320      66.588  68.652  80.833  0.00  0.00            
ATOM   5374  H6X POPC  320      67.406  68.956  81.486  0.00  0.00            
ATOM   5375  H6Y POPC  320      66.990  68.891  79.864  0.00  0.00            
ATOM   5376  C37 POPC  320      66.241  67.111  80.787  0.00  0.00            
ATOM   5377  H7X POPC  320      66.071  66.768  81.830  0.00  0.00            
ATOM   5378  H7Y POPC  320      67.161  66.656  80.505  0.00  0.00            
ATOM   5379  C38 POPC  320      65.221  66.685  79.698  0.00  0.00            
ATOM   5380  H8X POPC  320      64.239  67.059  80.033  0.00  0.00            
ATOM   5381  H8Y POPC  320      65.115  65.615  79.876  0.00  0.00            
ATOM   5382  C39 POPC  320      65.591  67.039  78.280  0.00  0.00            
ATOM   5383  H9X POPC  320      65.691  68.128  78.193  0.00  0.00            
ATOM   5384  H9Y POPC  320      66.617  66.672  78.173  0.00  0.00            
ATOM   5385 C310 POPC  320      64.593  66.556  77.229  0.00  0.00            
ATOM   5386 H10X POPC  320      63.604  67.013  77.453  0.00  0.00            
ATOM   5387 H10Y POPC  320      64.379  65.476  77.318  0.00  0.00            
ATOM   5388 C311 POPC  320      65.095  66.734  75.830  0.00  0.00            
ATOM   5389 H11X POPC  320      66.001  66.140  75.564  0.00  0.00            
ATOM   5390 H11Y POPC  320      65.263  67.769  75.453  0.00  0.00            
ATOM   5391 C312 POPC  320      64.061  66.172  74.852  0.00  0.00            
ATOM   5392 H12X POPC  320      63.618  65.145  75.180  0.00  0.00            
ATOM   5393 H12Y POPC  320      63.206  66.946  75.026  0.00  0.00            
ATOM   5394 C313 POPC  320      64.423  66.131  73.358  0.00  0.00            
ATOM   5395 H13X POPC  320      64.382  67.189  72.958  0.00  0.00            
ATOM   5396 H13Y POPC  320      63.685  65.552  72.842  0.00  0.00            
ATOM   5397 C314 POPC  320      65.869  65.675  73.070  0.00  0.00            
ATOM   5398 H14X POPC  320      66.684  66.391  73.520  0.00  0.00            
ATOM   5399 H14Y POPC  320      65.965  65.892  71.992  0.00  0.00            
ATOM   5400 C315 POPC  320      66.152  64.191  73.457  0.00  0.00            
ATOM   5401 H15X POPC  320      66.174  64.136  74.551  0.00  0.00            
ATOM   5402 H15Y POPC  320      65.332  63.543  73.055  0.00  0.00            
ATOM   5403 C316 POPC  320      67.389  63.619  72.780  0.00  0.00            
ATOM   5404 H16X POPC  320      67.670  62.614  73.105  0.00  0.00            
ATOM   5405 H16Y POPC  320      68.225  64.294  73.046  0.00  0.00            
ATOM   5406 H16Z POPC  320      67.340  63.696  71.628  0.00  0.00**

and this is supposedly the atom order of one POPC lipid molecule in OpenMM:
**HETATM    1  N   POP A   1      46.070   6.130  51.310  1.00  0.00           N  
HETATM    2  C12 POP A   1      45.890   7.600  51.630  1.00  0.00           C  
HETATM    3  C13 POP A   1      47.500   5.870  50.880  1.00  0.00           C  
HETATM    4  C14 POP A   1      45.890   5.350  52.590  1.00  0.00           C  
HETATM    5  C15 POP A   1      45.260   5.600  50.160  1.00  0.00           C  
HETATM    6 H12A POP A   1      46.080   8.080  50.680  1.00  0.00           H  
HETATM    7 H12B POP A   1      46.680   7.820  52.330  1.00  0.00           H  
HETATM    8 H13A POP A   1      47.640   4.820  50.700  1.00  0.00           H  
HETATM    9 H13B POP A   1      47.790   6.530  50.070  1.00  0.00           H  
HETATM   10 H13C POP A   1      48.140   6.090  51.710  1.00  0.00           H  
HETATM   11 H14A POP A   1      44.900   5.380  53.000  1.00  0.00           H  
HETATM   12 H14B POP A   1      46.060   4.300  52.450  1.00  0.00           H  
HETATM   13 H14C POP A   1      46.580   5.770  53.320  1.00  0.00           H  
HETATM   14 H15A POP A   1      45.520   4.560  50.000  1.00  0.00           H  
HETATM   15 H15B POP A   1      45.290   6.160  49.240  1.00  0.00           H  
HETATM   16 H15C POP A   1      44.210   5.800  50.350  1.00  0.00           H  
HETATM   17  C11 POP A   1      44.560   7.930  52.300  1.00  0.00           C  
HETATM   18 H11A POP A   1      44.540   8.980  52.650  1.00  0.00           H  
HETATM   19 H11B POP A   1      44.460   7.380  53.270  1.00  0.00           H  
HETATM   20  P   POP A   1      42.220   8.580  51.780  1.00  0.00           P  
HETATM   21  O13 POP A   1      41.790   8.470  53.190  1.00  0.00           O  
HETATM   22  O14 POP A   1      42.580   9.950  51.340  1.00  0.00           O  
HETATM   23  O12 POP A   1      43.470   7.660  51.420  1.00  0.00           O  
HETATM   24  O11 POP A   1      41.040   8.010  50.860  1.00  0.00           O  
HETATM   25  C1  POP A   1      40.830   6.600  50.960  1.00  0.00           C  
HETATM   26  HA  POP A   1      39.740   6.410  51.040  1.00  0.00           H  
HETATM   27  HB  POP A   1      41.290   6.150  51.870  1.00  0.00           H  
HETATM   28  C2  POP A   1      41.310   5.780  49.750  1.00  0.00           C  
HETATM   29  HS  POP A   1      42.400   5.660  49.940  1.00  0.00           H  
HETATM   30  O21 POP A   1      41.040   6.440  48.510  1.00  0.00           O  
HETATM   31  C21 POP A   1      42.070   7.060  47.910  1.00  0.00           C  
HETATM   32  O22 POP A   1      43.200   7.100  48.360  1.00  0.00           O  
HETATM   33  C22 POP A   1      41.580   7.550  46.560  1.00  0.00           C  
HETATM   34  H2R POP A   1      41.880   8.620  46.520  1.00  0.00           H  
HETATM   35  H2S POP A   1      40.470   7.620  46.500  1.00  0.00           H  
HETATM   36  C3  POP A   1      40.850   4.320  49.640  1.00  0.00           C  
HETATM   37  HX  POP A   1      39.770   4.240  49.380  1.00  0.00           H  
HETATM   38  HY  POP A   1      40.980   3.980  50.690  1.00  0.00           H  
HETATM   39  O31 POP A   1      41.630   3.650  48.640  1.00  0.00           O  
HETATM   40  C31 POP A   1      42.770   3.080  49.020  1.00  0.00           C  
HETATM   41  O32 POP A   1      43.380   3.380  50.030  1.00  0.00           O  
HETATM   42  C32 POP A   1      43.210   2.070  47.970  1.00  0.00           C  
HETATM   43  H2X POP A   1      42.510   1.210  47.920  1.00  0.00           H  
HETATM   44  H2Y POP A   1      44.220   1.710  48.280  1.00  0.00           H  
HETATM   45  C23 POP A   1      42.130   6.740  45.380  1.00  0.00           C  
HETATM   46  H3R POP A   1      42.230   5.670  45.640  1.00  0.00           H  
HETATM   47  H3S POP A   1      43.190   7.090  45.350  1.00  0.00           H  
HETATM   48  C24 POP A   1      41.410   7.010  44.060  1.00  0.00           C  
HETATM   49  H4R POP A   1      41.330   8.120  44.010  1.00  0.00           H  
HETATM   50  H4S POP A   1      40.430   6.490  44.000  1.00  0.00           H  
HETATM   51  C25 POP A   1      42.160   6.510  42.820  1.00  0.00           C  
HETATM   52  H5R POP A   1      41.530   6.600  41.910  1.00  0.00           H  
HETATM   53  H5S POP A   1      42.500   5.460  42.840  1.00  0.00           H  
HETATM   54  C26 POP A   1      43.350   7.420  42.510  1.00  0.00           C  
HETATM   55  H6R POP A   1      43.730   7.030  41.540  1.00  0.00           H  
HETATM   56  H6S POP A   1      44.220   7.230  43.170  1.00  0.00           H  
HETATM   57  C27 POP A   1      43.030   8.880  42.170  1.00  0.00           C  
HETATM   58  H7R POP A   1      43.920   9.360  41.700  1.00  0.00           H  
HETATM   59  H7S POP A   1      42.770   9.470  43.080  1.00  0.00           H  
HETATM   60  C28 POP A   1      41.830   9.070  41.250  1.00  0.00           C  
HETATM   61  H8R POP A   1      40.910   8.940  41.860  1.00  0.00           H  
HETATM   62  H8S POP A   1      41.780   8.320  40.430  1.00  0.00           H  
HETATM   63  C29 POP A   1      41.690  10.400  40.580  1.00  0.00           C  
HETATM   64  H91 POP A   1      41.220  11.160  41.220  1.00  0.00           H  
HETATM   65 C210 POP A   1      42.000  10.850  39.360  1.00  0.00           C  
HETATM   66 H101 POP A   1      41.860  11.900  39.050  1.00  0.00           H  
HETATM   67 C211 POP A   1      42.540   9.980  38.260  1.00  0.00           C  
HETATM   68 H11R POP A   1      42.740   8.960  38.670  1.00  0.00           H  
HETATM   69 H11S POP A   1      43.590  10.240  38.010  1.00  0.00           H  
HETATM   70 C212 POP A   1      41.650   9.700  37.050  1.00  0.00           C  
HETATM   71 H12R POP A   1      40.830   9.080  37.450  1.00  0.00           H  
HETATM   72 H12S POP A   1      42.180   9.010  36.350  1.00  0.00           H  
HETATM   73 C213 POP A   1      41.220  10.990  36.350  1.00  0.00           C  
HETATM   74 H13R POP A   1      42.110  11.640  36.250  1.00  0.00           H  
HETATM   75 H13S POP A   1      40.410  11.490  36.920  1.00  0.00           H  
HETATM   76 C214 POP A   1      40.580  10.590  35.010  1.00  0.00           C  
HETATM   77 H14R POP A   1      40.090   9.620  35.230  1.00  0.00           H  
HETATM   78 H14S POP A   1      41.450  10.290  34.390  1.00  0.00           H  
HETATM   79 C215 POP A   1      39.790  11.710  34.340  1.00  0.00           C  
HETATM   80 H15R POP A   1      40.450  12.500  33.920  1.00  0.00           H  
HETATM   81 H15S POP A   1      39.190  12.210  35.120  1.00  0.00           H  
HETATM   82 C216 POP A   1      38.920  11.150  33.210  1.00  0.00           C  
HETATM   83 H16R POP A   1      38.020  10.570  33.520  1.00  0.00           H  
HETATM   84 H16S POP A   1      39.490  10.500  32.520  1.00  0.00           H  
HETATM   85 C217 POP A   1      38.420  12.350  32.410  1.00  0.00           C  
HETATM   86 H17R POP A   1      37.870  11.930  31.540  1.00  0.00           H  
HETATM   87 H17S POP A   1      39.380  12.770  32.030  1.00  0.00           H  
HETATM   88 C218 POP A   1      37.620  13.330  33.260  1.00  0.00           C  
HETATM   89 H18R POP A   1      38.200  13.770  34.100  1.00  0.00           H  
HETATM   90 H18S POP A   1      36.830  12.690  33.710  1.00  0.00           H  
HETATM   91 H18T POP A   1      37.290  14.150  32.580  1.00  0.00           H  
HETATM   92  C33 POP A   1      43.270   2.740  46.590  1.00  0.00           C  
HETATM   93  H3X POP A   1      43.740   3.750  46.610  1.00  0.00           H  
HETATM   94  H3Y POP A   1      42.230   2.900  46.240  1.00  0.00           H  
HETATM   95  C34 POP A   1      43.930   1.880  45.510  1.00  0.00           C  
HETATM   96  H4X POP A   1      43.510   0.850  45.520  1.00  0.00           H  
HETATM   97  H4Y POP A   1      45.030   1.780  45.640  1.00  0.00           H  
HETATM   98  C35 POP A   1      43.600   2.250  44.060  1.00  0.00           C  
HETATM   99  H5X POP A   1      44.280   3.040  43.670  1.00  0.00           H  
HETATM  100  H5Y POP A   1      42.580   2.680  44.110  1.00  0.00           H  
HETATM  101  C36 POP A   1      43.660   1.000  43.180  1.00  0.00           C  
HETATM  102  H6X POP A   1      42.650   0.560  43.100  1.00  0.00           H  
HETATM  103  H6Y POP A   1      44.300   0.240  43.670  1.00  0.00           H  
HETATM  104  C37 POP A   1      44.110   1.420  41.770  1.00  0.00           C  
HETATM  105  H7X POP A   1      44.960   2.130  41.870  1.00  0.00           H  
HETATM  106  H7Y POP A   1      43.310   2.010  41.290  1.00  0.00           H  
HETATM  107  C38 POP A   1      44.450   0.270  40.820  1.00  0.00           C  
HETATM  108  H8X POP A   1      45.250  -0.390  41.220  1.00  0.00           H  
HETATM  109  H8Y POP A   1      44.810   0.710  39.870  1.00  0.00           H  
HETATM  110  C39 POP A   1      43.180  -0.480  40.420  1.00  0.00           C  
HETATM  111  H9X POP A   1      42.380   0.230  40.120  1.00  0.00           H  
HETATM  112  H9Y POP A   1      42.820  -1.130  41.250  1.00  0.00           H  
HETATM  113 C310 POP A   1      43.350  -1.240  39.100  1.00  0.00           C  
HETATM  114 H10X POP A   1      43.630  -0.520  38.310  1.00  0.00           H  
HETATM  115 H10Y POP A   1      42.360  -1.560  38.720  1.00  0.00           H  
HETATM  116 C311 POP A   1      44.390  -2.360  39.240  1.00  0.00           C  
HETATM  117 H11X POP A   1      44.310  -2.810  40.260  1.00  0.00           H  
HETATM  118 H11Y POP A   1      45.360  -1.880  39.010  1.00  0.00           H  
HETATM  119 C312 POP A   1      44.110  -3.440  38.200  1.00  0.00           C  
HETATM  120 H12X POP A   1      43.050  -3.720  38.370  1.00  0.00           H  
HETATM  121 H12Y POP A   1      44.790  -4.300  38.380  1.00  0.00           H  
HETATM  122 C313 POP A   1      44.400  -2.940  36.780  1.00  0.00           C  
HETATM  123 H13X POP A   1      45.170  -3.650  36.410  1.00  0.00           H  
HETATM  124 H13Y POP A   1      44.910  -1.960  36.770  1.00  0.00           H  
HETATM  125 C314 POP A   1      43.080  -2.980  35.990  1.00  0.00           C  
HETATM  126 H14X POP A   1      42.360  -2.370  36.580  1.00  0.00           H  
HETATM  127 H14Y POP A   1      42.730  -4.030  35.870  1.00  0.00           H  
HETATM  128 C315 POP A   1      43.270  -2.530  34.540  1.00  0.00           C  
HETATM  129 H15X POP A   1      43.620  -3.320  33.860  1.00  0.00           H  
HETATM  130 H15Y POP A   1      44.040  -1.730  34.610  1.00  0.00           H  
HETATM  131 C316 POP A   1      42.050  -1.810  33.950  1.00  0.00           C  
HETATM  132 H16X POP A   1      41.680  -1.080  34.700  1.00  0.00           H  
HETATM  133 H16Y POP A   1      41.280  -2.570  33.690  1.00  0.00           H  
HETATM  134 H16Z POP A   1      42.360  -1.200  33.070  1.00  0.00           H**  

While the atoms are the same between the two, the atom orders at the beginning are different, and that's why I ran into this error:

**ValueError: No template found for residue 320 (POPC).  The set of atoms matches POPC, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template**

I tried removing the hydrogen and asked Modeller in OpenMM to re-add them, but that did not work either. I wonder if there are any ways to solve this problem, still using the pdb file and OpenMM xml force field files to run the simulations?

**Comment by peastman** [comment]
This has nothing to do with the order of the atoms.  It only cares about the elements and the bonds between them.  See the FAQ entry linked in the error message.  It explains the different things that can cause this error, and what to do about them.

**Comment by hungd238** [comment]
Thank you very much for your time and insights, Dr. Eastman.
