### ISSUE TITLE
Protein-Ligand System

### ISSUE THREAD

**Issue by thegorilla10** [openmm/openmmforcefields#347]
I have a system that is a protein with a cofactor (FAD).
I am trying to generate the topology for this system.
In particular I am trying to do this:
Importing the topology for the ligand from a gromacs .top file
Generate the topology for the protein part with openmm-setup
Merge the two topologies
Run simulation using a .pdb file that contains everything.
I tried a lot of times but OpenMM never recognize the resiude.
I also tried to generate with openmmforcefields using SMILES but also if I do like this the program doesn't recognize the ligand.
Can someone help me ?

**Comment by mattwthompson** [comment]
I'll let the duplicate issue raised on the main tracker be the one
